[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = "src"
addopts = "-s --cov=src --cov-report=term-missing --cov-report=html"

[tool.mypy]
mypy_path = "src"
ignore_missing_imports = true

[tool.mutmut]
paths_to_mutate="src/"
tests_dir= "test/"
pythonpath = "src/"
debug= false 

